# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    filters:
      branches:
        only:
          - master

    steps:
      - checkout

      # Download and cache dependencies

      #command: ssh slboxer@hanainu.com -o StrictHostKeyChecking=no<<'cmd' "./deploy.sh" cmd
      - add_ssh_keys:
          fingerprints:
            - "08:6f:21:4a:d6:8c:b3:3a:4e:d2:1b:74:b3:e2:90:5e"

      - run: scp -o StrictHostKeyChecking=no -r ./* slboxer@hanainu.com:/home/slboxer/Webapp/amazon/

      - run:
          name: npm install
          command: ssh -t slboxer@hanainu.com -o StrictHostKeyChecking=no<< 'cd /home/slboxer/Webapp/amazon && sudo npm install'

workflows:
  version: 2
  build:
    jobs:
      - deploy
